version: "3"

services:
  rabbit:
    #image: rabbitmq:3.9-management
    build:
      context: ./bin
      dockerfile: Rabbitmq.Dockerfile
    hostname: rabbit
    container_name: rabbitmq3.9
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=123456
    volumes:
      - ./data:/var/lib/rabbitmq
